/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.StockManagement_UI;

import Management.StockManagement.*;
import Management.StockManagement.manager.MeatsManager;
import Management.StockManagement.manager.SauceManager;
import Management.StockManagement.manager.StaplesManager;
import Management.StockManagement.manager.VeggiesManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 남진우
 */
public class StockManager_UI extends javax.swing.JFrame {

    private DefaultTableModel stock_tm;  // stock 테이블모델
    private StockManagement s_manage;

    /**
     * Creates new form StockManager_UI
     */
    public StockManager_UI() {
        s_manage = new StockManagement();
        new MeatsManager().subscribeStockMangement(s_manage);
        new SauceManager().subscribeStockMangement(s_manage);
        new StaplesManager().subscribeStockMangement(s_manage);
        new VeggiesManager().subscribeStockMangement(s_manage);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        StockTable = new javax.swing.JTable();
        StockType = new javax.swing.JComboBox<>();
        selected_txt = new javax.swing.JLabel();
        selected_lb = new javax.swing.JLabel();
        paoPcs_lb = new javax.swing.JLabel();
        paoPcs_txt = new javax.swing.JTextField();
        propose_btn = new javax.swing.JButton();
        proposeApply_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        StockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
            },
            new String [] {
                "재고명", "열량", "단가","수량"
            }
        ));
        StockTable.setRowHeight(30);
        stock_tm = (DefaultTableModel) StockTable.getModel();
        StockTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        StockTable.getColumnModel().getColumn(1).setPreferredWidth(50);
        StockTable.getColumnModel().getColumn(2).setPreferredWidth(50);
        StockTable.getColumnModel().getColumn(3).setPreferredWidth(40);
        StockTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(StockTable);

        StockType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All","Staple", "Meat", "Sauce", "Veggie" }));
        StockType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockTypeActionPerformed(evt);
            }
        });

        selected_txt.setText("-");
        selected_txt.setHorizontalAlignment(javax.swing.JLabel.RIGHT);

        selected_lb.setText("선택 재고 :");

        paoPcs_lb.setText("발주 수량 :");

        paoPcs_txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        propose_btn.setText("발주 신청");
        propose_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propose_btnActionPerformed(evt);
            }
        });

        proposeApply_btn.setText("발주 완료");
        proposeApply_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proposeApply_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(selected_lb)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(selected_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(paoPcs_lb)
                                        .addGap(18, 18, 18)
                                        .addComponent(paoPcs_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(propose_btn)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(StockType, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(proposeApply_btn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(StockType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selected_txt)
                    .addComponent(selected_lb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paoPcs_lb)
                    .addComponent(paoPcs_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propose_btn))
                .addGap(18, 18, 18)
                .addComponent(proposeApply_btn)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StockTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockTableMouseClicked

        String mname = (String) StockTable.getValueAt(StockTable.getSelectedRow(), 0);
        selected_txt.setText(mname);

    }//GEN-LAST:event_StockTableMouseClicked

    private void StockTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockTypeActionPerformed
//        add.setTable((String)StockType.getSelectedItem(),tm);
        s_manage.setStocksTable((String) StockType.getSelectedItem(), stock_tm);
    }//GEN-LAST:event_StockTypeActionPerformed

    private void propose_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propose_btnActionPerformed
        // TODO add your handling code here:
        if (((String) StockType.getSelectedItem()).equals("All")) {

            int index = Integer.valueOf(paoPcs_txt.getText());
            JOptionPane.showMessageDialog(null, "모든재고의 발주를 신청하였습니다");
            s_manage.setAllStocksData(index);
            s_manage.setStocksTable((String) StockType.getSelectedItem(), stock_tm);
            paoPcs_txt.setText(null);
        } else {
            int index = Integer.valueOf(paoPcs_txt.getText());
            String sname = selected_txt.getText();
            JOptionPane.showMessageDialog(null, sname + "의 발주를 신청하였습니다");
            s_manage.setStocksData(sname, index);
            s_manage.setStocksTable((String) StockType.getSelectedItem(), stock_tm);
            paoPcs_txt.setText(null);
        }

    }//GEN-LAST:event_propose_btnActionPerformed

    private void proposeApply_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proposeApply_btnActionPerformed
        // TODO add your handling code here:
        s_manage.notifyStockManager();
    }//GEN-LAST:event_proposeApply_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockManager_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockManager_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockManager_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockManager_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockManager_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable StockTable;
    private javax.swing.JComboBox<String> StockType;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel paoPcs_lb;
    private javax.swing.JTextField paoPcs_txt;
    private javax.swing.JButton proposeApply_btn;
    private javax.swing.JButton propose_btn;
    private javax.swing.JLabel selected_lb;
    private javax.swing.JLabel selected_txt;
    // End of variables declaration//GEN-END:variables
}
