/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Main_UI;

import UI.MenuManagement_UI.MenuManager_UI;
import UI.OrderManagement_UI.Order_UI;
import UI.StockManagement_UI.StockManager_UI;
import java.util.Vector;
import javax.swing.JTextArea;

/**
 *
 * @author ³²Áø¿ì
 */
public class Main_UI extends javax.swing.JFrame {

    private Vector<Vector<Vector>> orderlists;
    private Vector<JTextArea> textareas;
    /**
     * Creates new form Main_UI
     */
    public Main_UI() {
        textareas = new Vector();
        orderlists = new Vector();
        setOrderLists();
        initComponents();
        setTextAreas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_area4 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_area1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Table_area2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        Table_area3 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        Table_area5 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        Table_area6 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        Table_area7 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        Table_area8 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        Table_area9 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        Table_area10 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        Table_area11 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        Table_area12 = new javax.swing.JTextArea();
        StockManager_btn = new javax.swing.JButton();
        MenuManager_btn = new javax.swing.JButton();
        SalesManager_btn = new javax.swing.JButton();
        ReceiptManager_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Table_area4.setColumns(5);
        Table_area4.setRows(5);
        Table_area4.setText("4");
        Table_area4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_area4MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table_area4);

        Table_area1.setColumns(5);
        Table_area1.setFont(new java.awt.Font("¸¼Àº °íµñ", 0, 10)); // NOI18N
        Table_area1.setRows(5);
        Table_area1.setText("1");
        Table_area1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_area1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Table_area1);

        Table_area2.setColumns(5);
        Table_area2.setFont(new java.awt.Font("¸¼Àº °íµñ", 0, 10)); // NOI18N
        Table_area2.setRows(5);
        Table_area2.setText("2");
        Table_area2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_area2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Table_area2);

        Table_area3.setColumns(5);
        Table_area3.setFont(new java.awt.Font("¸¼Àº °íµñ", 0, 10)); // NOI18N
        Table_area3.setLineWrap(true);
        Table_area3.setRows(5);
        Table_area3.setText("3");
        Table_area3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_area3MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(Table_area3);

        Table_area5.setColumns(5);
        Table_area5.setRows(5);
        Table_area5.setText("5");
        Table_area5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_area5MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(Table_area5);

        Table_area6.setColumns(5);
        Table_area6.setRows(5);
        Table_area6.setText("6");
        Table_area6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_area6MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(Table_area6);

        Table_area7.setColumns(5);
        Table_area7.setRows(5);
        Table_area7.setText("7");
        Table_area7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_area7MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(Table_area7);

        Table_area8.setColumns(5);
        Table_area8.setRows(5);
        Table_area8.setText("8");
        Table_area8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_area8MouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(Table_area8);

        Table_area9.setColumns(5);
        Table_area9.setRows(5);
        Table_area9.setText("9");
        Table_area9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_area9MouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(Table_area9);

        Table_area10.setColumns(5);
        Table_area10.setRows(5);
        Table_area10.setText("10");
        Table_area10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_area10MouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(Table_area10);

        Table_area11.setColumns(5);
        Table_area11.setRows(5);
        Table_area11.setText("11");
        Table_area11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_area11MouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(Table_area11);

        Table_area12.setColumns(5);
        Table_area12.setRows(5);
        Table_area12.setText("12");
        Table_area12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_area12MouseClicked(evt);
            }
        });
        jScrollPane13.setViewportView(Table_area12);

        StockManager_btn.setText("Àç°í °ü¸®");
        StockManager_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockManager_btnActionPerformed(evt);
            }
        });

        MenuManager_btn.setText("¸Þ´º °ü¸®");
        MenuManager_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuManager_btnActionPerformed(evt);
            }
        });

        SalesManager_btn.setText("¼öÀÍ °ü¸®");
        SalesManager_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesManager_btnActionPerformed(evt);
            }
        });

        ReceiptManager_btn.setText("¿µ¼öÁõ °ü¸®");
        ReceiptManager_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiptManager_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MenuManager_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(StockManager_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SalesManager_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ReceiptManager_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StockManager_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(53, 53, 53)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MenuManager_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(SalesManager_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReceiptManager_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Table_area1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_area1MouseClicked
        // TODO add your handling code here:
        int index = 0;
        Order_UI ou = new Order_UI(textareas.get(index),index, orderlists.get(index),this);
        orderlists.set(index, ou.order.getOrderList());
        ou.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Table_area1MouseClicked

    private void Table_area2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_area2MouseClicked
        // TODO add your handling code here:
        int index = 1;;
        Order_UI ou = new Order_UI(textareas.get(index),index, orderlists.get(index),this);
        orderlists.set(index, ou.order.getOrderList());
        ou.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Table_area2MouseClicked

    private void Table_area3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_area3MouseClicked
        // TODO add your handling code here:
        int index = 2;
        Order_UI ou = new Order_UI(textareas.get(index),index, orderlists.get(index),this);
        orderlists.set(index, ou.order.getOrderList());
        ou.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Table_area3MouseClicked

    private void Table_area4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_area4MouseClicked
        // TODO add your handling code here:
        int index = 3;
        Order_UI ou = new Order_UI(textareas.get(index),index, orderlists.get(index),this);
        orderlists.set(index, ou.order.getOrderList());
        ou.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Table_area4MouseClicked

    private void Table_area5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_area5MouseClicked
        // TODO add your handling code here:
        int index = 4;
        Order_UI ou = new Order_UI(textareas.get(index),index, orderlists.get(index),this);
        orderlists.set(index, ou.order.getOrderList());
        ou.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Table_area5MouseClicked

    private void Table_area6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_area6MouseClicked
        // TODO add your handling code here:
        int index = 5;
        Order_UI ou = new Order_UI(textareas.get(index),index, orderlists.get(index),this);
        orderlists.set(index, ou.order.getOrderList());
        ou.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Table_area6MouseClicked

    private void Table_area7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_area7MouseClicked
        // TODO add your handling code here:
        int index = 6;
        Order_UI ou = new Order_UI(textareas.get(index),index, orderlists.get(index),this);
        orderlists.set(index, ou.order.getOrderList());
        ou.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Table_area7MouseClicked

    private void Table_area8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_area8MouseClicked
        // TODO add your handling code here:
        int index = 7;
        Order_UI ou = new Order_UI(textareas.get(index),index, orderlists.get(index),this);
        orderlists.set(index, ou.order.getOrderList());
        ou.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Table_area8MouseClicked

    private void Table_area9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_area9MouseClicked
        // TODO add your handling code here:
        int index = 8;
        Order_UI ou = new Order_UI(textareas.get(index),index, orderlists.get(index),this);
        orderlists.set(index, ou.order.getOrderList());
        ou.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Table_area9MouseClicked

    private void Table_area10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_area10MouseClicked
        // TODO add your handling code here:
        int index = 9;
        Order_UI ou = new Order_UI(textareas.get(index),index, orderlists.get(index),this);
        orderlists.set(index, ou.order.getOrderList());
        ou.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Table_area10MouseClicked

    private void Table_area11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_area11MouseClicked
        // TODO add your handling code here
        int index = 10;
        Order_UI ou = new Order_UI(textareas.get(index),index, orderlists.get(index),this);
        orderlists.set(index, ou.order.getOrderList());
        ou.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Table_area11MouseClicked

    private void Table_area12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_area12MouseClicked
        // TODO add your handling code here:
        int index = 11;
        Order_UI ou = new Order_UI(textareas.get(index),index, orderlists.get(index),this);
        orderlists.set(index, ou.order.getOrderList());
        ou.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Table_area12MouseClicked

    private void StockManager_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockManager_btnActionPerformed
        // TODO add your handling code here:
        new StockManager_UI().setVisible(true);
    }//GEN-LAST:event_StockManager_btnActionPerformed

    private void MenuManager_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuManager_btnActionPerformed
        // TODO add your handling code here:
        new MenuManager_UI().setVisible(true);
    }//GEN-LAST:event_MenuManager_btnActionPerformed

    private void SalesManager_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesManager_btnActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_SalesManager_btnActionPerformed

    private void ReceiptManager_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiptManager_btnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ReceiptManager_btnActionPerformed

    private void setOrderLists(){
        orderlists.add(new Vector<Vector>());//1
        orderlists.add(new Vector<Vector>());//2
        orderlists.add(new Vector<Vector>());//3
        orderlists.add(new Vector<Vector>());//4
        orderlists.add(new Vector<Vector>());//5
        orderlists.add(new Vector<Vector>());//6
        orderlists.add(new Vector<Vector>());//7
        orderlists.add(new Vector<Vector>());//8
        orderlists.add(new Vector<Vector>());//9
        orderlists.add(new Vector<Vector>());//10
        orderlists.add(new Vector<Vector>());//11
        orderlists.add(new Vector<Vector>());//12
    }
    private void setTextAreas(){
        textareas.add(Table_area1);
        textareas.add(Table_area2);
        textareas.add(Table_area3);
        textareas.add(Table_area4);
        textareas.add(Table_area5);
        textareas.add(Table_area6);
        textareas.add(Table_area7);
        textareas.add(Table_area8);
        textareas.add(Table_area9);
        textareas.add(Table_area10);
        textareas.add(Table_area11);
        textareas.add(Table_area12);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuManager_btn;
    private javax.swing.JButton ReceiptManager_btn;
    private javax.swing.JButton SalesManager_btn;
    private javax.swing.JButton StockManager_btn;
    private javax.swing.JTextArea Table_area1;
    private javax.swing.JTextArea Table_area10;
    private javax.swing.JTextArea Table_area11;
    private javax.swing.JTextArea Table_area12;
    private javax.swing.JTextArea Table_area2;
    private javax.swing.JTextArea Table_area3;
    private javax.swing.JTextArea Table_area4;
    private javax.swing.JTextArea Table_area5;
    private javax.swing.JTextArea Table_area6;
    private javax.swing.JTextArea Table_area7;
    private javax.swing.JTextArea Table_area8;
    private javax.swing.JTextArea Table_area9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
}
