/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.PayManagement_UI;

import Management.OrderManagement.Order.*;
import Management.PayManagement.discount.*;
import java.util.*;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 남진우
 */
public class Discount_UI extends javax.swing.JFrame {

    public ArrayList<JButton> p_btnlist;
    public Vector av;
    private Object[][] ob;
    private Discount disc;
    private boolean adisc_flag = true;
    private boolean tdisc_flag = true;

    // setAmounts로 받아온 값
    Order od;
    DefaultTableModel dtm;
    int index;

    /**
     * Creates new form Discount_UI
     */
    public Discount_UI(Object[][] ob, ArrayList<JButton> p_btnlist) {
        this.p_btnlist = p_btnlist;
        this.ob = ob;
        initComponents();
        total_txt.setText(String.valueOf(ob[0][1]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        total_lb = new javax.swing.JLabel();
        total_txt = new javax.swing.JLabel();
        payType_lb = new javax.swing.JLabel();
        payType_cbx = new javax.swing.JComboBox<>();
        Affiliate_chx = new javax.swing.JCheckBox();
        Affiliate_cbx = new javax.swing.JComboBox<>();
        Telecom_chx = new javax.swing.JCheckBox();
        Telecom_cbx = new javax.swing.JComboBox<>();
        Cash_chx = new javax.swing.JCheckBox();
        Cash_cbx = new javax.swing.JComboBox<>();
        dicount_lb = new javax.swing.JLabel();
        discount_txt = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        tobeReceive_lb = new javax.swing.JLabel();
        tobeReceive_txt = new javax.swing.JLabel();
        ok_btn = new javax.swing.JButton();
        applydisc_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        total_lb.setText("총 금 액 :");

        total_txt.setText("");

        payType_lb.setText("결제수단");

        payType_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  "카드", "모바일","현금"}));
        payType_cbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payType_cbxActionPerformed(evt);
            }
        });

        Affiliate_chx.setText("제휴 할인");
        Affiliate_chx.setEnabled(false);
        Affiliate_chx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Affiliate_chxActionPerformed(evt);
            }
        });

        Affiliate_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "우리은행", "기업은행", "카카오뱅크", "토스뱅크" }));
        Affiliate_cbx.setEnabled(false);
        Affiliate_cbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Affiliate_cbxActionPerformed(evt);
            }
        });

        Telecom_chx.setText("통신사 할인");
        Telecom_chx.setEnabled(false);
        Telecom_chx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Telecom_chxActionPerformed(evt);
            }
        });

        Telecom_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SKT", "KT", "LGU+" }));
        Telecom_cbx.setEnabled(false);
        Telecom_cbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Telecom_cbxActionPerformed(evt);
            }
        });

        Cash_chx.setText("현금 할인");
        Cash_chx.setEnabled(false);
        Cash_chx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cash_chxActionPerformed(evt);
            }
        });

        Cash_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "포장", "쿠폰"}));
        Cash_cbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cash_cbxActionPerformed(evt);
            }
        });
        Cash_cbx.setEnabled(false);

        dicount_lb.setText("할인금액 :");

        discount_txt.setText(String.valueOf(ob[1][1]));

        tobeReceive_lb.setText("받을금액 :");

        tobeReceive_txt.setText(String.valueOf(ob[2][1]));

        ok_btn.setText("확인");
        ok_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_btnActionPerformed(evt);
            }
        });

        applydisc_btn.setText("할인 적용");
        applydisc_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applydisc_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ok_btn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tobeReceive_lb)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tobeReceive_txt))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(dicount_lb)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(discount_txt))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Affiliate_chx)
                            .addGap(18, 18, 18)
                            .addComponent(Affiliate_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(payType_lb)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(payType_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(total_lb)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(total_txt))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Telecom_chx)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Telecom_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Cash_chx)
                            .addGap(18, 18, 18)
                            .addComponent(Cash_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1)
                        .addComponent(jSeparator2)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(applydisc_btn))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total_lb)
                    .addComponent(total_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payType_lb)
                    .addComponent(payType_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Affiliate_chx)
                    .addComponent(Affiliate_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telecom_chx)
                    .addComponent(Telecom_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cash_chx)
                    .addComponent(Cash_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(applydisc_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(discount_txt)
                    .addComponent(dicount_lb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tobeReceive_lb)
                    .addComponent(tobeReceive_txt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ok_btn)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ok_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_btnActionPerformed
        System.out.println(payType_cbx.getSelectedIndex());
        switch (payType_cbx.getSelectedIndex()) {
            case 0:
                p_btnlist.get(0).setEnabled(false);
                p_btnlist.get(1).setEnabled(true);
                p_btnlist.get(2).setEnabled(false);
                break;
            case 1:
                p_btnlist.get(0).setEnabled(false);
                p_btnlist.get(1).setEnabled(false);
                p_btnlist.get(2).setEnabled(true);
                break;
            case 2:
                p_btnlist.get(0).setEnabled(true);
                p_btnlist.get(1).setEnabled(false);
                p_btnlist.get(2).setEnabled(false);
                break;
        }
        od.setAmounts(dtm, index);
        dtm.setRowCount(0);
        
        dtm.setDataVector(ob, new Object[]{"결제","정보"});
        dtm.fireTableDataChanged();
        
        
        this.dispose();
    }//GEN-LAST:event_ok_btnActionPerformed

    private void payType_cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payType_cbxActionPerformed
        // TODO add your handling code here:
        Affiliate_chx.setEnabled(false);
        Affiliate_cbx.setEnabled(false);
        Affiliate_chx.setSelected(false);

        Telecom_chx.setEnabled(false);
        Telecom_cbx.setEnabled(false);
        Telecom_chx.setSelected(false);

        Cash_chx.setEnabled(false);
        Cash_cbx.setEnabled(false);
        Cash_chx.setSelected(false);

        switch ((String) payType_cbx.getSelectedItem()) {

            case "현금":
                Cash_chx.setEnabled(true);
                break;
            case "카드":
                Affiliate_chx.setEnabled(true);
                Telecom_chx.setEnabled(true);
                break;
            case "모바일":
                Affiliate_chx.setEnabled(true);
                Telecom_chx.setEnabled(true);
                break;
        }


    }//GEN-LAST:event_payType_cbxActionPerformed

    private void Affiliate_chxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Affiliate_chxActionPerformed
        // TODO add your handling code here:


        if (Affiliate_chx.isSelected()) Affiliate_cbx.setEnabled(true);
        else Affiliate_cbx.setEnabled(false);
    }//GEN-LAST:event_Affiliate_chxActionPerformed

    private void Telecom_chxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Telecom_chxActionPerformed
        // TODO add your handling code here:
        if (Telecom_chx.isSelected()) Telecom_cbx.setEnabled(true);
        else Telecom_cbx.setEnabled(false);
    }//GEN-LAST:event_Telecom_chxActionPerformed

    private void Cash_chxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cash_chxActionPerformed
        // TODO add your handling code here:
        if (Cash_chx.isSelected()) Cash_cbx.setEnabled(true);
        else Cash_cbx.setEnabled(false);
        
    }//GEN-LAST:event_Cash_chxActionPerformed

    private void Affiliate_cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Affiliate_cbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Affiliate_cbxActionPerformed

    private void Telecom_cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Telecom_cbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Telecom_cbxActionPerformed

    private void applydisc_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applydisc_btnActionPerformed
        // TODO add your handling code here:
        disc = new BaseDiscount((int) ob[0][1]);
        if(Affiliate_chx.isSelected())disc = new AffiliateDiscount(disc, (String) Affiliate_cbx.getSelectedItem());
        if(Telecom_chx.isSelected())disc = new TelecomDiscount(disc, (String) Telecom_cbx.getSelectedItem());
        if(Cash_chx.isSelected()) disc = new CashDiscount(disc,(String)Cash_cbx.getSelectedItem());
        ob[1][1] = (int) ob[0][1] - disc.applyDiscount();
        ob[2][1] = disc.applyDiscount();
        ob[4][1] = (int) ob[3][1] - disc.applyDiscount(); // 거스름돈
        discount_txt.setText(String.valueOf(ob[1][1]));
        tobeReceive_txt.setText(String.valueOf(ob[2][1]));
        
        
    }//GEN-LAST:event_applydisc_btnActionPerformed

    private void Cash_cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cash_cbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cash_cbxActionPerformed
    public void setAmounts(Order od, DefaultTableModel dtm, int index) {
        this.od = od;
        this.dtm = dtm;
        this.index = index;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Discount_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Discount_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Discount_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Discount_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Discount_UI(ob,new ArrayList()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Affiliate_cbx;
    private javax.swing.JCheckBox Affiliate_chx;
    private javax.swing.JComboBox<String> Cash_cbx;
    private javax.swing.JCheckBox Cash_chx;
    private javax.swing.JComboBox<String> Telecom_cbx;
    private javax.swing.JCheckBox Telecom_chx;
    private javax.swing.JButton applydisc_btn;
    private javax.swing.JLabel dicount_lb;
    private javax.swing.JLabel discount_txt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton ok_btn;
    private javax.swing.JComboBox<String> payType_cbx;
    private javax.swing.JLabel payType_lb;
    private javax.swing.JLabel tobeReceive_lb;
    private javax.swing.JLabel tobeReceive_txt;
    private javax.swing.JLabel total_lb;
    private javax.swing.JLabel total_txt;
    // End of variables declaration//GEN-END:variables
}
