/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.OrderManagement_UI;

import Management.MenuManagement.Menu.Menu;
import Management.OrderManagement.Order.*;
import UI.Main_UI.Main_UI;
import UI.PayManagement_UI.*;
import java.util.*;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 남진우
 */
public class Order_UI extends javax.swing.JFrame {

    private DefaultTableModel amountsmodel;
    private DefaultTableModel otm;
    private ArrayList<JButton> btnlist;
    private ArrayList<JButton> p_btnlist;
    private int tobeReceive_amount = 0;

    public Order order;

    //받아온 값
    private JTextArea ta;
    private int index;
    private Main_UI mu;

    /**
     * Creates new form Order_UI
     */
    public Order_UI(JTextArea ta, int index, Vector<Vector> orderlist, Main_UI mu) {
        this.ta = ta;
        this.index = index;
        this.mu = mu;

        order = new Order();
        if (!ta.getText().equals(String.valueOf(index))) {
            order.orderlist = orderlist;
        }
        initComponents();
        order.takeOrder(otm);

        setbtnlist();
        setPayment_btnlist();
        order.getbtnList(btnlist);
        order.setEnableF();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        AmountTable = new javax.swing.JTable();
        btn_1 = new javax.swing.JButton();
        amount_field = new javax.swing.JTextField();
        Enter_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Category1 = new javax.swing.JButton();
        Category2 = new javax.swing.JButton();
        Category3 = new javax.swing.JButton();
        Category5 = new javax.swing.JButton();
        Category4 = new javax.swing.JButton();
        mbtn_1 = new javax.swing.JButton();
        mbtn_2 = new javax.swing.JButton();
        mbtn_3 = new javax.swing.JButton();
        mbtn_4 = new javax.swing.JButton();
        mbtn_5 = new javax.swing.JButton();
        mbtn_6 = new javax.swing.JButton();
        mbtn_7 = new javax.swing.JButton();
        mbtn_8 = new javax.swing.JButton();
        mbtn_9 = new javax.swing.JButton();
        mbtn_10 = new javax.swing.JButton();
        mbtn_11 = new javax.swing.JButton();
        mbtn_12 = new javax.swing.JButton();
        mbtn_13 = new javax.swing.JButton();
        mbtn_14 = new javax.swing.JButton();
        mbtn_15 = new javax.swing.JButton();
        CashPayment_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        CardPayment_btn = new javax.swing.JButton();
        MobilePayment_btn = new javax.swing.JButton();
        ApplyOrder_btn = new javax.swing.JButton();
        Exit_btn = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_C = new javax.swing.JButton();
        Discount_btn = new javax.swing.JButton();
        allClear_btn = new javax.swing.JButton();
        selectClear_btn = new javax.swing.JButton();
        pcsChange_btn = new javax.swing.JButton();
        plus_btn = new javax.swing.JButton();
        minus_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        OrderTable.setAutoCreateRowSorter(true);
        OrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                //        "*","메뉴명","단가","수량","할인","금액"
                "Num","메뉴명","단가","수량","금액"
            }
        ));
        otm = (DefaultTableModel) OrderTable.getModel();
        OrderTable.setEnabled(true);
        OrderTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        OrderTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        OrderTable.getColumnModel().getColumn(2).setPreferredWidth(40);
        OrderTable.getColumnModel().getColumn(3).setPreferredWidth(20);
        OrderTable.getColumnModel().getColumn(4).setPreferredWidth(60);
        OrderTable.setFillsViewportHeight(true);
        OrderTable.setRowSelectionAllowed(true);
        OrderTable.setShowGrid(false);
        jScrollPane1.setViewportView(OrderTable);

        AmountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"총 금 액", null},
                {"할인금액", null},
                {"받을금액", null},
                {"받은금액", null},
                {"거스름돈", null}
            },
            new String [] {
                "결제", "정보"
            }
        ));
        AmountTable.setRowHeight(38);
        amountsmodel = (DefaultTableModel) AmountTable.getModel();
        jScrollPane2.setViewportView(AmountTable);

        btn_1.setText("1");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        amount_field.setText(String.valueOf(tobeReceive_amount));
        amount_field.setHorizontalAlignment(JTextField.RIGHT);
        amount_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount_fieldActionPerformed(evt);
            }
        });

        Enter_btn.setText("Enter");
        Enter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enter_btnActionPerformed(evt);
            }
        });

        Category1.setText("R&Ns");
        Category1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category1ActionPerformed(evt);
            }
        });

        Category2.setText("Meats");
        Category2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category2ActionPerformed(evt);
            }
        });

        Category3.setText("Sides");
        Category3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category3ActionPerformed(evt);
            }
        });

        Category5.setText("음료");
        Category5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category5ActionPerformed(evt);
            }
        });

        Category4.setText("Salad");
        Category4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category4ActionPerformed(evt);
            }
        });

        mbtn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_1ActionPerformed(evt);
            }
        });

        mbtn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_2ActionPerformed(evt);
            }
        });

        mbtn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_3ActionPerformed(evt);
            }
        });

        mbtn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_4ActionPerformed(evt);
            }
        });

        mbtn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_5ActionPerformed(evt);
            }
        });

        mbtn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_6ActionPerformed(evt);
            }
        });

        mbtn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_7ActionPerformed(evt);
            }
        });

        mbtn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_8ActionPerformed(evt);
            }
        });

        mbtn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_9ActionPerformed(evt);
            }
        });

        mbtn_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_10ActionPerformed(evt);
            }
        });

        mbtn_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_11ActionPerformed(evt);
            }
        });

        mbtn_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_12ActionPerformed(evt);
            }
        });

        mbtn_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_13ActionPerformed(evt);
            }
        });

        mbtn_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_14ActionPerformed(evt);
            }
        });

        mbtn_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtn_15ActionPerformed(evt);
            }
        });

        CashPayment_btn.setText("현금");
        CashPayment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashPayment_btnActionPerformed(evt);
            }
        });

        CardPayment_btn.setText("카드");
        CardPayment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardPayment_btnActionPerformed(evt);
            }
        });

        MobilePayment_btn.setText("모바일");
        MobilePayment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobilePayment_btnActionPerformed(evt);
            }
        });

        ApplyOrder_btn.setText("주문");
        ApplyOrder_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyOrder_btnActionPerformed(evt);
            }
        });

        Exit_btn.setText("취소");
        Exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(mbtn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mbtn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mbtn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(Category1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Category2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Category3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Category4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Category5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(mbtn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mbtn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mbtn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(mbtn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mbtn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mbtn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(mbtn_10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mbtn_11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mbtn_12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(mbtn_13, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mbtn_14, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mbtn_15, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ApplyOrder_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Exit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CashPayment_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(CardPayment_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MobilePayment_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Category1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Category2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Category3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Category5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Category4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mbtn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbtn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbtn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mbtn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbtn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbtn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mbtn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbtn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbtn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mbtn_10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbtn_12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbtn_11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mbtn_13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbtn_15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbtn_14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MobilePayment_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CardPayment_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CashPayment_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ApplyOrder_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Exit_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        btn_2.setText("2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setText("3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_4.setText("4");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_7.setText("7");
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_remove.setText("<");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        btn_0.setText("0");
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_C.setText("C");
        btn_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CActionPerformed(evt);
            }
        });

        Discount_btn.setText("할인");
        Discount_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Discount_btnActionPerformed(evt);
            }
        });

        allClear_btn.setText("전체취소");
        allClear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allClear_btnActionPerformed(evt);
            }
        });

        selectClear_btn.setText("선택취소");

        pcsChange_btn.setText("수량변경");

        plus_btn.setText("+");
        plus_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_btnActionPerformed(evt);
            }
        });

        minus_btn.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(amount_field, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_C, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Discount_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(Enter_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(allClear_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectClear_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pcsChange_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plus_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minus_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(allClear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectClear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pcsChange_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plus_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minus_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(amount_field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Discount_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_C, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Enter_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Enter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enter_btnActionPerformed

        if (order.orderlist.isEmpty()) {
            JOptionPane.showMessageDialog(null, "메뉴를 입력해주시기 바랍니다.");
        } else {
            order.setAmounts(amountsmodel, Integer.parseInt(amount_field.getText()));
        }

    }//GEN-LAST:event_Enter_btnActionPerformed

    private void amount_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount_fieldActionPerformed

    private void CardPayment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardPayment_btnActionPerformed
        // TODO add your handling code here:
        CardPayment_UI cpu = new CardPayment_UI(order.ocal.ob, p_btnlist);
        cpu.setAmounts(order, amountsmodel, Integer.parseInt(amount_field.getText()));
        cpu.setVisible(true);
    }//GEN-LAST:event_CardPayment_btnActionPerformed

    private void Category4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category4ActionPerformed
        String s = "Salads";
        order.setMenus(s);
    }//GEN-LAST:event_Category4ActionPerformed

    private void Category5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category5ActionPerformed
        String s = "Beverages";
        order.setMenus(s);
    }//GEN-LAST:event_Category5ActionPerformed

    private void Category3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category3ActionPerformed
        String s = "SideDishs";
        order.setMenus(s);
    }//GEN-LAST:event_Category3ActionPerformed

    private void Category2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category2ActionPerformed
        String s = "Meats";
        order.setMenus(s);
    }//GEN-LAST:event_Category2ActionPerformed

    private void Category1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category1ActionPerformed
        String s = "Rice&Noodles";
        order.setMenus(s);
    }//GEN-LAST:event_Category1ActionPerformed

    private void MobilePayment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobilePayment_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobilePayment_btnActionPerformed

    private void Discount_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Discount_btnActionPerformed
        // TODO add your handling code here:
        try {
            Discount_UI du = new Discount_UI(order.ocal.ob, p_btnlist);
            du.setAmounts(order, amountsmodel, Integer.parseInt(amount_field.getText()));
            du.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "받은 돈을 입력해주시기 바랍니다.");
        }


    }//GEN-LAST:event_Discount_btnActionPerformed

    private void mbtn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_1ActionPerformed
        // TODO add your handling code here:
        order.addOrder(mbtn_1.getText(), otm);
        order.setAmounts(amountsmodel, Integer.parseInt(amount_field.getText()));
    }//GEN-LAST:event_mbtn_1ActionPerformed

    private void mbtn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_2ActionPerformed
        // TODO add your handling code here:
        order.addOrder(mbtn_2.getText(), otm);
        order.setAmounts(amountsmodel, Integer.parseInt(amount_field.getText()));
    }//GEN-LAST:event_mbtn_2ActionPerformed

    private void mbtn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_3ActionPerformed
        // TODO add your handling code here:
        order.addOrder(mbtn_3.getText(), otm);
        order.setAmounts(amountsmodel, Integer.parseInt(amount_field.getText()));
    }//GEN-LAST:event_mbtn_3ActionPerformed

    private void mbtn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_4ActionPerformed
        // TODO add your handling code here:
        order.addOrder(mbtn_4.getText(), otm);
        order.setAmounts(amountsmodel, Integer.parseInt(amount_field.getText()));
    }//GEN-LAST:event_mbtn_4ActionPerformed

    private void mbtn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_5ActionPerformed
        // TODO add your handling code here:
        order.addOrder(mbtn_5.getText(), otm);
        order.setAmounts(amountsmodel, Integer.parseInt(amount_field.getText()));
    }//GEN-LAST:event_mbtn_5ActionPerformed

    private void mbtn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_6ActionPerformed
        // TODO add your handling code here:
        order.addOrder(mbtn_6.getText(), otm);
        order.setAmounts(amountsmodel, Integer.parseInt(amount_field.getText()));
    }//GEN-LAST:event_mbtn_6ActionPerformed

    private void mbtn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_7ActionPerformed
        // TODO add your handling code here:
        order.addOrder(mbtn_1.getText(), otm);
        order.setAmounts(amountsmodel, Integer.parseInt(amount_field.getText()));
    }//GEN-LAST:event_mbtn_7ActionPerformed

    private void plus_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plus_btnActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
        tobeReceive_amount = tobeReceive_amount * 10 + 1;
        amount_field.setText(String.valueOf(tobeReceive_amount));
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:
        tobeReceive_amount = tobeReceive_amount * 10 + 2;
        amount_field.setText(String.valueOf(tobeReceive_amount));
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:
        tobeReceive_amount = tobeReceive_amount * 10 + 3;
        amount_field.setText(String.valueOf(tobeReceive_amount));
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // TODO add your handling code here:
        tobeReceive_amount = tobeReceive_amount * 10 + 4;
        amount_field.setText(String.valueOf(tobeReceive_amount));
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        // TODO add your handling code here:
        tobeReceive_amount = tobeReceive_amount * 10 + 5;
        amount_field.setText(String.valueOf(tobeReceive_amount));
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        // TODO add your handling code here:
        tobeReceive_amount = tobeReceive_amount * 10 + 6;
        amount_field.setText(String.valueOf(tobeReceive_amount));
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        // TODO add your handling code here:
        tobeReceive_amount = tobeReceive_amount * 10 + 7;
        amount_field.setText(String.valueOf(tobeReceive_amount));
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        // TODO add your handling code here:
        tobeReceive_amount = tobeReceive_amount * 10 + 8;
        amount_field.setText(String.valueOf(tobeReceive_amount));
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        // TODO add your handling code here:
        tobeReceive_amount = tobeReceive_amount * 10 + 9;
        amount_field.setText(String.valueOf(tobeReceive_amount));
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        // TODO add your handling code here:
        tobeReceive_amount = tobeReceive_amount * 10;
        amount_field.setText(String.valueOf(tobeReceive_amount));
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CActionPerformed
        // TODO add your handling code here:
        tobeReceive_amount = 0;
        amount_field.setText(String.valueOf(tobeReceive_amount));
    }//GEN-LAST:event_btn_CActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:

        tobeReceive_amount = tobeReceive_amount / 10;
        amount_field.setText(String.valueOf(tobeReceive_amount));
    }//GEN-LAST:event_btn_removeActionPerformed

    private void mbtn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbtn_8ActionPerformed

    private void mbtn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbtn_9ActionPerformed

    private void mbtn_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbtn_10ActionPerformed

    private void mbtn_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbtn_11ActionPerformed

    private void mbtn_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbtn_12ActionPerformed

    private void mbtn_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbtn_13ActionPerformed

    private void mbtn_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbtn_14ActionPerformed

    private void mbtn_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtn_15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbtn_15ActionPerformed

    private void allClear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allClear_btnActionPerformed
        // TODO add your handling code here:
        order.orderlist.removeAllElements();
        otm.setRowCount(0);
        otm.fireTableDataChanged();
        order.setAmounts(amountsmodel, 0);
    }//GEN-LAST:event_allClear_btnActionPerformed

    private void CashPayment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashPayment_btnActionPerformed
        // TODO add your handling code here:
        new CashPayment_UI(order.getOrderList()).setVisible(true);
    }//GEN-LAST:event_CashPayment_btnActionPerformed

    private void ApplyOrder_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyOrder_btnActionPerformed
        // TODO add your handling code here:

        ta.setText("");
        ta.append((index + 1) + "    " + order.ob[0][1] + "\n");
        for (Vector vec : order.orderlist) {
            ta.append(vec.get(1).toString() + "   " + vec.get(3) + "\n");
        }
        mu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ApplyOrder_btnActionPerformed

    private void Exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_btnActionPerformed
        // TODO add your handling code here
        order.orderlist.removeAllElements();
        otm.setRowCount(0);
        otm.fireTableDataChanged();
        order.setAmounts(amountsmodel, 0);
        mu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Exit_btnActionPerformed

    private void setbtnlist() {

        btnlist = new ArrayList<JButton>();
        btnlist.add(mbtn_1);
        btnlist.add(mbtn_2);
        btnlist.add(mbtn_3);
        btnlist.add(mbtn_4);
        btnlist.add(mbtn_5);
        btnlist.add(mbtn_6);
        btnlist.add(mbtn_7);
        btnlist.add(mbtn_8);
        btnlist.add(mbtn_9);
        btnlist.add(mbtn_10);
        btnlist.add(mbtn_11);
        btnlist.add(mbtn_12);
        btnlist.add(mbtn_13);
        btnlist.add(mbtn_14);
        btnlist.add(mbtn_15);
    }

    private void setPayment_btnlist() {
        p_btnlist = new ArrayList();
        p_btnlist.add(CashPayment_btn);
        p_btnlist.add(CardPayment_btn);
        p_btnlist.add(MobilePayment_btn);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Order_UI(new JTextArea()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AmountTable;
    private javax.swing.JButton ApplyOrder_btn;
    private javax.swing.JButton CardPayment_btn;
    private javax.swing.JButton CashPayment_btn;
    private javax.swing.JButton Category1;
    private javax.swing.JButton Category2;
    private javax.swing.JButton Category3;
    private javax.swing.JButton Category4;
    private javax.swing.JButton Category5;
    private javax.swing.JButton Discount_btn;
    private javax.swing.JButton Enter_btn;
    private javax.swing.JButton Exit_btn;
    private javax.swing.JButton MobilePayment_btn;
    private javax.swing.JTable OrderTable;
    private javax.swing.JButton allClear_btn;
    private javax.swing.JTextField amount_field;
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_C;
    private javax.swing.JButton btn_remove;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mbtn_1;
    private javax.swing.JButton mbtn_10;
    private javax.swing.JButton mbtn_11;
    private javax.swing.JButton mbtn_12;
    private javax.swing.JButton mbtn_13;
    private javax.swing.JButton mbtn_14;
    private javax.swing.JButton mbtn_15;
    private javax.swing.JButton mbtn_2;
    private javax.swing.JButton mbtn_3;
    private javax.swing.JButton mbtn_4;
    private javax.swing.JButton mbtn_5;
    private javax.swing.JButton mbtn_6;
    private javax.swing.JButton mbtn_7;
    private javax.swing.JButton mbtn_8;
    private javax.swing.JButton mbtn_9;
    private javax.swing.JButton minus_btn;
    private javax.swing.JButton pcsChange_btn;
    private javax.swing.JButton plus_btn;
    private javax.swing.JButton selectClear_btn;
    // End of variables declaration//GEN-END:variables
}
